### ISSUE TITLE
Help: Versioning issue, lost my work

### ISSUE THREAD

**Issue by couture322** [eco-detectives/primer_of_ecology_r#8]
Hi all,
Team Nudi is having some issues with versioning on our doc. I did some work yesterday (7/15), commit and pushed 3 times. Something happened since then and my edits aren't on our doc :( . When you look at the repo commit history, you see [my commits](https://github.com/eco-detectives/primer_of_ecology_r/commit/5aab8f30bd89925771dfd4f398ec00920e3577c6), but if you look at the [history of the ch1_teamNudi.Rmd](https://github.com/eco-detectives/primer_of_ecology_r/commits/master/ch1/ch1_teamNudi.Rmd) file I have no edits for over a week. 

It sounds like team would be happy to revert to the last commit I made but I'm confused about why its not in the history and what the best way forward is for us.

**Comment by jcvdav** [comment]
Interesting, I can see the commit messages multiple times looking at the [blame](https://github.com/eco-detectives/primer_of_ecology_r/blame/5aab8f30bd89925771dfd4f398ec00920e3577c6/ch1/ch1_teamNudi.Rmd). It looks like it might be worth looking at your local history (`git log`) or even Sean's.

Also, what happens if you do `git prune`?

I wouldn't revert the repo because we would lose all changes, but I think you could rescue your work from the diffed changes in the link to your commit from two weeks ago, or some careful branching, reverting, revaseing and merging?

**Comment by couture322** [comment]
Thanks @jcvdav sounds messy tho.

 I just pasted my code chunks back into the nudi rmd the old fashioned way and they are showing up for now. But am still concerned that the past commits aren't showing up in our history, including commits from @AlbertogGarcia and @vthivierge. it looks like only @seanmdenny has done anything when you look at the rmd history :/

**Comment by couture322** [comment]
We decided to give up on this, but think it had something to do with the merge conflicts when pushing the fig files made when knitting. Fixed the figs issue by removing fig.path argument, (see issue #9)
