### ISSUE TITLE
How do we stop writing all the fig files every time we knit?

### ISSUE THREAD

**Issue by couture322** [eco-detectives/primer_of_ecology_r#9]
Team nudi has had a lot of issues with conflicts with the figures being reproduced every time we knit, so when we commit and try to push there are almost always conflicts with the existing fig files. 

This might have been part of the cause of the lost history in the ch1_teamNudi.rmd file defined in issue #8

**Comment by couture322** [comment]
I removed the 'fig.path' argument from the `opts_chunk$set` and the figs aren't being written anymore 👍 

@jcvdav mentioned last week that the the figs are helpful when sharing the knit html/pdfs externally, could you explain why/when we'd want those fig files?

**Comment by couture322** [comment]
@oharac also deleted this argument from the other groups rmds and deleted the fig folder, so everyone should pull to update the files and rmds

**Comment by oharac** [comment]
Let's close this issue and hope that it's all good from now on!

**Comment by jcvdav** [comment]
Sorry, I hadn't seen this. FWIW, you can specify a custom `figs` path where the figures will be exported to. Here's how I make sense of it (it might be wrong):

# No `fig.path` specified

When you knit an Rmd file, the first thing that happens is that all code chunks are executed. If these code chunks happen to produce figures that will be in your document (note that no call to `ggsave` or anything like that is needed!), `knitr` will export those figures using the default dimensions and as `*.png`s to `test_files/`. It'll save them with file names corresponding to code chunk labels. At this point, all R code has been executed, but the final document (whatever the format is) does not exist.

The figure below shows how R code is executed (red line shows this).

![image](https://user-images.githubusercontent.com/11950459/61908213-10d9da80-aee4-11e9-866b-72539c4f51d3.png)

The next step is for pandoc to take the text (not code) in the Rmd and create a makrdown (NOT RMarkdown) file. Usually, you'll see a `test.knit.md` pop up and disappear every time you knit `test.Rmd`. (see the last line of the above image). In this new, temporary `*.md` file, images that were originally produced by R code are included using standard markdown syntax (*i.e.* `![image1.png](test_files/image1.)`. This implies that images must be read from somewhare! Thankfully, `knitr` created a temporary directory where all figures were stored. These can now be read!

## When knitting to html

Since the `html` document generated is self-contained by default, the temporary figures repository is deleted. If you were to use `self_contained: no` (or something like that), then the directory will not be removed. This is very useful, for example, for `blogdown` or `bookdown`.

## When knitting to pdf

This involves an additional process, in which the `*.md` file needs to be converted to a `*.tex` file. That is, a full LaTeX file containing the original text in the Rmd, but converted to LaTeX syntax, as well as calls to include images (in this case, with `\includegraphics{test_files}` and all that stuff...). If you were to set `keep_tex: yes`, then the intermediate tex file will not be removed after compilation.

# Specifying a `fig.path`

Now, this is all great and nice. It certainly simplifies everything for us. But... we all know how journals always want you to submit your figures separately, just to append them to your MS anyway (at least natural science journals!). If we wanted to submit this for publication, we have a problem: our figures don't exist because they have been removed after compilation! How do we fix this?

If we were creating an html file, we could have just set the `self_contained: no` and that would have created an image folder with some cryptic and predetermined names. But we are likely submitting in pdf (or worst, docx) format! Another solution is to specify something like `, fig.path = "figs/"`, which will export all figures to that folder. Then, when the time to submit comes, I can just go into that folder and upload my figures into the system.

# How to deal with the merging problems?

There are a couple of options:

- add the `figs` path to the `.gitignore` file (not recommended, but works)
- make all `git`-related opperations from the terminal (available within Rstudio ince the 1.2 release) instead of the `git` ui tab (it's know to cause lots of issues).
